### ISSUE TITLE
payload data type

### ISSUE THREAD

**Issue by jberkel** [googollee/go-gcm#1]
hi, thanks for this code, it was useful as a starting point. however i think SetPayload should only accept strings, since the gcm docs state:

The values could be any JSON object, but we recommend using strings, since the values will be converted to strings in the GCM server anyway.

http://developer.android.com/guide/google/gcm/gcm.html#request

avoids some potential confusion

**Comment by googollee** [comment]
You are right, thanks. I have pushed the update. ;)

On Fri, Oct 12, 2012 at 2:53 AM, Jan Berkel notifications@github.comwrote:

> hi, thanks for this code, it was useful as a starting point. however i
> think SetPayload should only accept strings, since the gcm docs state:
> 
> The values could be any JSON object, but we recommend using strings, since
> the values will be converted to strings in the GCM server anyway.
> 
> http://developer.android.com/guide/google/gcm/gcm.html#request
> 
> avoids some potential confusion
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/googollee/go-gcm/issues/1.

## 

新的理论从少数人的主张到一统天下，并不是因为这个理论说服了别人抛弃旧观点，而是因为一代人的逝去。
